[project]
name = "nextwork-rag-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "chromadb>=1.4.1",
    "fastapi[standard]>=0.128.5",
    "ollama>=0.6.1",
    "uvicorn>=0.40.0",
]
